### ISSUE TITLE
Missing DLL on Windows 11 installtion

### ISSUE THREAD

**Issue by sanyaade-teachings** [hangrydave/InfraredBrickTower#33]
Hi Everybody,

Many thanks for this project and for keeping it alive for the Lego communities.
I got an error when trying to install the package on Windows 11 (64 Bit)
![image](https://github.com/hangrydave/InfraredBrickTower/assets/4993211/34afb935-8be8-4871-9741-d962b50db8a0)

Missing DLL so the application aborted

Please help!

God blesses!!!

Regards

**Comment by hangrydave** [comment]
Hello! Thanks for bringing this to my attention. I've published a new release, v1.1a, that addresses this issue. The required DLL file is now included within the release.

[https://github.com/hangrydave/InfraredBrickTower/releases/tag/v1.1a](https://github.com/hangrydave/InfraredBrickTower/releases/tag/v1.1a)

Thanks again!
